### ISSUE TITLE
Label format about Center coordinates

### ISSUE THREAD

**Issue by Dana136484** [JDSobek/MedYOLO#13]
Hello, sorry to bother you. In README: Center coordinates should fall between -0.5 and 1.5,  I just know box coordinates can be in normalized zxydwh format from 0 to 1. So how could I process label(box coordinates) to let the centre coordinates fall between -0.5 and 1.5? Thank you!
![屏幕截图 2024-04-11 161432](https://github.com/JDSobek/MedYOLO/assets/126674286/dbc717bb-b991-4688-a684-3670db486462)

**Comment by JDSobek** [comment]
Sorry if I misunderstand your question, but coordinates between 0 and 1 are also between -0.5 and 1.5.

I think the outer limits extend beyond 0 and 1 out to -0.5 and 1.5 so the original 2D framework can handle detected objects that are partially/mostly out of frame. It's allowed as a natural consequence of the formula used to convert the model's output into normalized coordinates, so there wasn't a downside to keeping that functionality in 3D. I don't know much about ultrasound, but that might be a modality where it could be useful.
