### ISSUE TITLE
hello，Can you tell me how to convert tag format to txt in dataset?

### ISSUE THREAD

**Issue by 15266249311** [JDSobek/MedYOLO#14]
hello，Can you tell me how to convert tag format to txt in dataset?

**Comment by JDSobek** [comment]
I don't think I've worked with tag format before (tiff files?). [I have this script that I use for converting NIfTI segmentations to txt bounding box labels.](https://github.com/JDSobek/PublicMLCode/blob/main/seg_to_MedYOLO_txt.py) If you can load your data into numpy arrays, you should be able to adapt that script to work for your data.

**Comment by 15266249311** [comment]
发自我的iPhone


------------------ Original ------------------
From: JDSobek ***@***.***&gt;
Date: Thu,May 2,2024 10:47 PM
To: JDSobek/MedYOLO ***@***.***&gt;
Cc: 15266249311 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [JDSobek/MedYOLO] hello，Can you tell me how to convert tag format to txt in dataset? (Issue #14)





 
I don't think I've worked with tag format before (tiff files?). I have this script that I use for converting NIfTI segmentations to txt bounding box labels. If you can load your data into numpy arrays, you should be able to adapt that script to work for your data.

**Comment by 15266249311** [comment]
Can you make that txt conversion script public on GitHub?



发自我的iPhone


------------------ Original ------------------
From: JDSobek ***@***.***&gt;
Date: Thu,May 2,2024 10:47 PM
To: JDSobek/MedYOLO ***@***.***&gt;
Cc: 15266249311 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [JDSobek/MedYOLO] hello，Can you tell me how to convert tag format to txt in dataset? (Issue #14)





 
I don't think I've worked with tag format before (tiff files?). I have this script that I use for converting NIfTI segmentations to txt bounding box labels. If you can load your data into numpy arrays, you should be able to adapt that script to work for your data.

**Comment by JDSobek** [comment]
It should be public already, at least the link works for me while I'm not logged-in.

**Comment by 15266249311** [comment]
> It should be public already, at least the link works for me while I'm not logged-in.

Hi, is the file converted to txt format a seg_to_MedYOLO_txt file? And what was the file format before conversion?

**Comment by JDSobek** [comment]
Yes that is the name of the python script. It extracts text labels for objects found in NIfTI segmentation masks. However, it does not work if there are multiple objects of the same class in the mask, and you will have to rewrite the file loading to read in your files if they are not NIfTI files.
