### ISSUE TITLE
Is segmenting tumor compartments possible?

### ISSUE THREAD

**Issue by selayav** [JDSobek/MedYOLO#19]
Is segmenting brain tumors on MRI scans into edema, necrosis and enhancing tumor possible with MedYOLO?

Thanks!

**Comment by JDSobek** [comment]
Segmentation isn't something the model can do. I tested whole tumor detection/bounding box generation on BRaTS and got pretty good results, about what I got from nnDetection, but I didn't try to break the task down into detecting tumor components. I would guess necrotic core detection is plausible alongside detecting the whole tumor volume, but the rectangular boxes the model generates aren't going to be voxel-accurate. It may be useful for narrowing down the input volume for a downstream segmentation model, though.

I didn't get a chance to try this, but if you wanted to train on BRaTS I would try adding rotated examples like I describe doing for the abdominal dataset in the paper. My training runs suggested to me some uncaptured performance that needs additional augmentation to access.
