### ISSUE TITLE
A question about Center coordinates

### ISSUE THREAD

**Issue by yingao123** [JDSobek/MedYOLO#26]
I doubt why "Center coordinates should fall between -0.5 and 1.5." They are the fraction of the width and height, shouldn't they fall between 0.0 to 1.0?

**Comment by JDSobek** [comment]
It's to accommodate objects that are centered outside the image. I don't know when this would be useful in medical imaging, perhaps in some ultrasound images or near the top/bottom of a scan, but it was a natural consequence of using YOLOv5's formula for processing predictions.

The edges of the image are still 0 and 1, you just have the capability of annotating/detecting objects that aren't fully in-frame, as long as they are centered close enough to 0 and 1.
