### ISSUE TITLE
About the label.

### ISSUE THREAD

**Issue by mawei-north** [JDSobek/MedYOLO#27]
May I ask how the label file for your dataset is (.txt) generated or made? What software was used to achieve this?

**Comment by JDSobek** [comment]
I use [this script](https://github.com/JDSobek/PublicMLCode/blob/main/seg_to_MedYOLO_txt.py) to convert semantic segmentations into the bounding box txt labels for MedYOLO. It's a fairly simple script though (it only looks for 1 bounding box for each class), and for some datasets, like LIDC, the instance segmentations available in the dataset allow you to do some more sophisticated labeling than my script can do. I generated my segmentations with RIL-Contour, but any nifti segmentation masks will work.

I'd recommend using my script with a grain of salt, in case your dataset or your goal with the model requires more complex processing than mine did.
