### ISSUE TITLE
Clarification about Table 1 in the paper

### ISSUE THREAD

**Issue by aymuos15** [JDSobek/MedYOLO#28]
Is there any benchmark for MedYOLO-S with batchsize 2 and 350 edge length? Any reason why this was missed out?

Thanks a lot for open-sourcing this!

**Comment by JDSobek** [comment]
For the most part the benchmarks were for experiments I ran on the GPU I had, which was a reasonably large (~40 GB) card. From a quick test, that configuration needs just under 12 GB for single-class bounding boxes, may be a bit more for multi-class problems but I don't remember that being a huge contributor to VRAM demands.
