### ISSUE TITLE
weights for lung nodule

### ISSUE THREAD

**Issue by Sere1nz** [JDSobek/MedYOLO#9]
Hi, 
Great paper! I am interested in med3d detection. Could you provide trained weight for LIDC or luna16(lung nodule)? Thank you very much!

**Comment by JDSobek** [comment]
Unfortunately no.  I did try to train on LIDC several times, but the model never managed to identify them.  My impression is that lung nodules are too small for the model to detect.  I've seen recent success on fairly small objects, but nothing that small.

There may be some tricks to make lung nodule detection work, but in the meantime [nnDetection](https://github.com/MIC-DKFZ/nnDetection) has pretrained weights for LIDC and luna16 so I'd suggest their model over this one for lung nodule detection.
